### ISSUE TITLE
AssertionError: Collection was loaded during event handling.

### ISSUE THREAD

**Issue by pyfection** [pyfection/strategos#2]
I could not figure out why this comes up. It happens on controller.actor.world.World.distribute_tiles when a relationship of a Tile is set (tile.owner). This only happens if the original owner was not None and once it is set, the owner can be changed without issues. It also doesn't seem to be a timing issue or threading (threading is not used at this point).

```
>>> world.distribute_tiles()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/strategos/controller/actor/world.py", line 34, in distribute_tiles
    tile.owner = actor
  File "/strategos/controller/base.py", line 32, in __setattr__
    self.MODEL.__setattr__(self._model, key, value)
  File "/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 812, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 834, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 1172, in emit_backref_from_scalar_set_event
    passive=PASSIVE_NO_FETCH)
  File "/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 1025, in pop
    self.remove(state, dict_, value, initiator, passive=passive)
  File "/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 1015, in remove
    "Collection was loaded during event handling."
AssertionError: Collection was loaded during event handling.
```

**Comment by pyfection** [comment]
SQLAlchemy no longer used
